syntax = "proto3";
option go_package = "github.com/headblockhead/railreader-grpc";

import "railtypes.proto";

message DisruptionReason {
    uint32 reason_id = 1;
    optional string reason_location_id = 2;
    // When true, the provided reason_id is 'near to' the provided reason_location_id. 
    // When false, the reason_id is 'at' the reason_location_id.
    bool reason_is_near_location = 3;  
}

message DescribeResponse {
    message Schedule {
        string uuid = 1;
        reserved 2 to 3;
        string schedule_id = 4;
        string uid = 5;
        reserved 6 to 7;
        string headcode = 8;
        optional string retail_service_id = 9;
        string toc_id = 10;
        ServiceType service = 11;
        CategoryType category = 12;
        bool is_passenger_service = 13;
        bool is_active = 14;
        reserved 15;
        bool is_charter = 16;
        bool is_cancelled = 17;
        optional DisruptionReason cancellation_reason = 18;
        optional string diverted_via_location_id = 19;
        optional DisruptionReason diversion_reason = 20;
    }
    repeated Schedule schedules = 1;

    message Formation {

    }
    repeated Formation formations = 2;

    message RouteLocation {
        message RouteLocationEdge {
            message ScheduleEdge {
                string schedule_location_uuid = 1;
            }
            message AssociationEdge {
                string schedule_location_uuid = 1;
                AssociationCategory association_category = 2;
                bool is_cancelled = 3;
            }
            oneof edge {
                ScheduleEdge schedule_edge = 1;
                AssociationEdge association_edge = 2;
            }
        }
        repeated RouteLocationEdge next_edges = 1;
        repeated RouteLocationEdge previous_edges = 2;
    
        reserved 3 to 4;
    
        // 'Working' times are used internally by staff
        // 'Public' times are used for display to passengers
        // Working and Public timetables may differ, typically to allow services to experience very minor (30 to 60s) delays without appearing late to the public.
        // There is no scheduled_public_passing_time because locations through which a service passes without stopping do not need to display any times to the public.
        message ScheduleLocation {
            string uuid = 1;
            string schedule_uuid = 2;
            uint32 schedule_order = 3;
            string location_id = 4;
            repeated ActivityType activities = 5;
            repeated ActivityType planned_activities = 6;
            optional string formation_id = 7;
            bool is_affected_by_diversion = 8;
            enum LocationType {
                LOCATION_TYPE_LOCATION_UNKNOWN = 0;
                LOCATION_TYPE_LOCATION_ORIGIN = 1;
                LOCATION_TYPE_LOCATION_OPERATIONAL_ORIGIN = 2;
                LOCATION_TYPE_LOCATION_INTERMEDIATE = 3;
                LOCATION_TYPE_LOCATION_OPERATIONAL_INTERMEDIATE = 4;
                LOCATION_TYPE_LOCATION_INTERMEDIATE_PASSING = 5;
                LOCATION_TYPE_LOCATION_DESTINATION = 6;
                LOCATION_TYPE_LOCATION_OPERATIONAL_DESTINATION = 7;
            }
            LocationType type = 9;
            optional string working_arrival_time = 10;
            optional string working_passing_time = 11; 
            optional string working_departure_time = 12;
            optional string public_arrival_time = 13; 
            optional string public_departure_time = 14;
            uint32 routing_delay = 15; // in minutes
            optional string false_destination_location_id = 16;
            bool is_cancelled = 17;
            optional DisruptionReason location_cancellation_reason = 18;
            optional string timetabled_platform = 19;
        }
        ScheduleLocation schedule_location = 5;
    
        reserved 6 to 11;

        optional string current_platform = 12;
        optional string generous_arrival_time = 13;
        optional string generous_passing_time = 14;
        optional string generous_departure_time = 15;
    }
    repeated RouteLocation route = 3;

    string requested_schedule_location_uuid = 4;
}
