syntax = "proto3";
option go_package = "github.com/headblockhead/railreader-grpc";

import "railtypes.proto";

message DescribeResponse {
    string requested_schedule_location_uuid = 1;

    message Schedule {
        string uuid = 1;
        reserved 2 to 3;
        string schedule_id = 4;
        string uid = 5;
        reserved 6 to 7;
        string headcode = 8;
        optional string retail_service_id = 9;
        string toc_id = 10;
        ServiceType service = 11;
        CategoryType category = 12;
        bool is_passenger_service = 13;
        bool is_active = 14;
        reserved 15;
        bool is_charter = 16;
        bool is_cancelled = 17;
        optional DisruptionReason cancellation_reason = 18;
        optional string diverted_via_location_id = 19;
        optional DisruptionReason diversion_reason = 20;

        message Forecast {
            reserved 1 to 3;
            bool is_reverse_formation = 4;
            optional DisruptionReason late_reason = 5;
        }
        optional Forecast forecast = 21;
    }
    repeated Schedule schedules = 2;

    message Formation {
        reserved 1 to 3;
        string formation_id = 4;
        optional string source = 5;
        optional string source_system = 6;
        message Coach {
            reserved 1;
            string identifier = 2;
            optional string class = 3;
            message Toilet {
                string type = 1;
                enum Status {
                    STATUS_UNKNOWN = 0;
                    STATUS_IN_SERVICE = 1;
                    STATUS_NOT_IN_SERVICE = 2;
                }
                Status status = 2;
            }
            optional Toilet toilet_data = 4;
        }
        repeated Coach coaches = 7;
    }
    repeated Formation formations = 3;

    message RouteLocation {
        message Edge {
            message Schedule {
                string schedule_location_uuid = 1;
            }
            message Association {
                string schedule_location_uuid = 1;
                AssociationCategory association_category = 2;
                bool is_cancelled = 3;
            }
            oneof edge {
                Schedule schedule = 1;
                Association association = 2;
            }
        }
        repeated Edge next_edges = 1;
        repeated Edge previous_edges = 2;

        optional string via_text = 3;

        message ForecastLocation {
            reserved 1 to 8;
            message Times {
                optional string estimated_public_time = 1;
                optional string estimated_working_time = 2;
                optional string minimum_estimated_time = 3;
                bool estimation_manually_set_to_delayed = 4;
                bool estimated_as_delayed = 5;
                optional string actual_time = 6;
                optional string actual_time_class = 7;
                optional string source = 8;
                optional string source_system = 9;
            }
            optional Times arrival = 9;
            optional Times passing = 10;
            optional Times departure = 11;
            optional DisruptionReason late_reason = 12;
            optional string disruption_risk = 13;
            optional DisruptionReason disruption_risk_reason = 14;
            optional string affected_by = 15;
            optional uint32 forecast_length = 16;
            message Platform {
                bool is_suppressed = 1;
                bool is_manually_suppressed_by_cis = 2;
                string source = 3;
                bool is_confirmed = 4;
                string platform = 5;
            }
            optional Platform forecast_platform = 17;
            bool service_is_suppressed_here = 18;
            bool service_detaches_from_front_here = 19;
        }
        optional ForecastLocation forecast_location = 4;

        message FormationLoading {
            reserved 1 to 10;
            message Coach {
                reserved 1;
                string identifier = 2;
                optional string source = 3;
                optional string source_system = 4;
                uint32 percentage_load = 5;
            }
            repeated Coach coaches = 11;
        }  
        optional FormationLoading formation_loading = 5;
  
        // 'Working' times are used internally by staff
        // 'Public' times are used for display to passengers
        // Working and Public timetables may differ, typically to allow services to experience very minor (30 to 60s) delays without appearing late to the public.
        // There is no scheduled_public_passing_time because locations through which a service passes without stopping do not need to display any times to the public.
        message ScheduleLocation {
            string uuid = 1;
            string schedule_uuid = 2;
            reserved 3;
            string location_id = 4;
            repeated ActivityType activities = 5;
            repeated ActivityType planned_activities = 6;
            optional string formation_id = 7;
            bool is_affected_by_diversion = 8;
            enum Type {
                TYPE_LOCATION_UNKNOWN = 0;
                TYPE_LOCATION_ORIGIN = 1;
                TYPE_LOCATION_OPERATIONAL_ORIGIN = 2;
                TYPE_LOCATION_INTERMEDIATE = 3;
                TYPE_LOCATION_OPERATIONAL_INTERMEDIATE = 4;
                TYPE_LOCATION_INTERMEDIATE_PASSING = 5;
                TYPE_LOCATION_DESTINATION = 6;
                TYPE_LOCATION_OPERATIONAL_DESTINATION = 7;
            }
            Type type = 9;
            optional string working_arrival_time = 10;
            optional string working_passing_time = 11; 
            optional string working_departure_time = 12;
            optional string public_arrival_time = 13; 
            optional string public_departure_time = 14;
            int32 routing_delay = 15; // in minutes
            optional string false_destination_location_id = 16;
            bool is_cancelled = 17;
            optional DisruptionReason location_cancellation_reason = 18;
            optional string timetabled_platform = 19;
        }
        ScheduleLocation schedule_location = 6;

        message ServiceLoading {
            reserved 1 to 9;
            enum Type {
                TYPE_LOADING_UNKNOWN = 0;
                TYPE_LOADING_TYPICAL = 1;
                TYPE_LOADING_EXPECTED = 2;
            } 
            message Category {
                string code = 1;
                optional string source = 2;
                optional string source_system = 3;
                Type type = 4;
            }
            optional Category category = 10;
            message Percentage {
                uint32 percentage_load = 1;
                optional string source = 2;
                optional string source_system = 3;
                Type type = 4;
            }
            optional Percentage percentage = 11;
        }
        optional ServiceLoading service_loading = 7;

        // TODO: Train alerts
        reserved 8 to 12;

        optional string generous_arrival_time = 13;
        optional string generous_passing_time = 14;
        optional string generous_departure_time = 15;
    }
    repeated RouteLocation route = 4;
}

message DisruptionReason {
    uint32 reason_id = 1;
    optional string reason_location_id = 2;
    // When true, the provided reason_id is 'near to' the provided reason_location_id. 
    // When false, the reason_id is 'at' the reason_location_id.
    bool reason_is_near_location = 3;  
}
