syntax = "proto3";
option go_package = "github.com/headblockhead/railreader-grpc";

// The locationUpdates system assumes your client will store an array of changes to the locations list over time, and make periodical (minimum once after passing ~03:30AM each day) calls to keep said array of changes up-to-date from the server.

// To get changes to the locations list from the start of availiable data, call without including a from_reference_file_id.
message LocationUpdatesRequest {
    optional string from_reference_file_id = 1;
}

message LocationUpdate {
    string reference_file_id = 6; // The reference_file_id at which this change occurred. 
    string location_id = 1; // TIPLOC
    bool is_deleted = 5;
    optional string crs_id = 2;
    optional string toc_id = 3;
    string name = 4;
}

message LocationUpdateResponse {
   string to_reference_file_id = 1; // The lastest reference_file_id equivalent you will have after applying all updates.
   repeated LocationUpdate updates = 2;
}
