syntax = "proto3";
option go_package = "github.com/headblockhead/railreader-grpc";

enum ServiceType {
    SERVICE_TYPE_SERVICE_UNKNOWN = 0;

    SERVICE_TYPE_SERVICE_TRAIN = 1;
    SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_TRAIN = 2;
    SERVICE_TYPE_SERVICE_BUS = 3;
    SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_BUS = 4;
    SERVICE_TYPE_SERVICE_SHIP = 5;
    SERVICE_TYPE_SERVICE_SHORT_TERM_PLANNED_SHIP = 6;
    // Trip and Freight types ommitted as they are not tracked by Darwin
}

enum ActivityType {
    ACTIVITY_TYPE_ACTIVITY_UNKNOWN = 0;
    
    ACTIVITY_TYPE_ACTIVITY_TRAIN_BEGINS = 1;
    ACTIVITY_TYPE_ACTIVITY_TRAIN_FINISHES = 2;
    
    ACTIVITY_TYPE_ACTIVITY_STOPS_TO_TAKE_UP_AND_SET_DOWN_PASSENGERS = 3;
    ACTIVITY_TYPE_ACTIVITY_STOPS_TO_TAKE_UP_PASSENGERS = 4;
    ACTIVITY_TYPE_ACTIVITY_STOPS_TO_SET_DOWN_PASSENGERS = 5;
    
    ACTIVITY_TYPE_ACTIVITY_STOPS_OR_SHUNTS_FOR_OTHER_TRAINS_TO_PASS = 6;
    ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_OR_DETACH_ASSISTING_LOCOMOTIVE = 7;
    ACTIVITY_TYPE_ACTIVITY_SHOWS_AS_X_ON_ARRIVAL = 8;
    ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_OR_DETACH_BANKING_LOCOMOTIVE = 9; 
    ACTIVITY_TYPE_ACTIVITY_STOPS_TO_CHANGE_TRAIN_CREW = 10; 
    ACTIVITY_TYPE_ACTIVITY_STOPS_TO_DETATCH_VEHICLES = 11; 
    ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_EXAMINATION = 12; 
    ACTIVITY_TYPE_ACTIVITY_NATIONAL_RAIL_TIMETABLE_DATA_TO_ADD = 13; 
    ACTIVITY_TYPE_ACTIVITY_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE = 14;
    ACTIVITY_TYPE_ACTIVITY_NOTIONAL_ACTIVITY_TO_PREVENT_WTT_TIMING_COLUMNS_MERGE_TWICE = 15;
    ACTIVITY_TYPE_ACTIVITY_PASSENGER_COUNT_POINT = 16;
    ACTIVITY_TYPE_ACTIVITY_TICKET_COLLECTION_AND_EXAMINATION_POINT = 17;
    ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT = 18;
    ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT_FIRST_CLASS_ONLY = 19;
    ACTIVITY_TYPE_ACTIVITY_TICKET_EXAMINATION_POINT_SELECTIVE = 20;
    ACTIVITY_TYPE_ACTIVITY_STOPS_TO_CHANGE_LOCOMOTIVES = 21;
    ACTIVITY_TYPE_ACTIVITY_STOP_NOT_ADVERTISED = 22;
    ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_OTHER_OPERATING_REASONS = 23;
    ACTIVITY_TYPE_ACTIVITY_TRAIN_LOCOMOTIVE_ON_REAR = 24;
    ACTIVITY_TYPE_ACTIVITY_PROPELLING_BETWEEN_POINTS_SHOWN = 25;
    ACTIVITY_TYPE_ACTIVITY_STOPS_WHEN_REQUIRED = 26;
    ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_REVERSING_MOVEMENT_OR_DRIVER_END_CHANGE = 27;
    ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_LOCOMOTIVE_TO_RUN_ROUND = 28;
    ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_RAILWAY_PERSONELL_ONLY = 29;
    ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_AND_DETACH_VEHICLES = 30;
    ACTIVITY_TYPE_ACTIVITY_DETAIL_CONSIST_FOR_TOPS_DIRECT = 31;
    ACTIVITY_TYPE_ACTIVITY_STOPS_OR_PASSES_FOR_TABLET_STAFF_OR_TOKEN = 32;
    ACTIVITY_TYPE_ACTIVITY_STOPS_TO_ATTACH_VEHICLES = 33;
    ACTIVITY_TYPE_ACTIVITY_STOPS_FOR_WATERING_OF_COACHES = 34;
    ACTIVITY_TYPE_ACTIVITY_PASSES_ANOTHER_TRAIN_AT_CROSSING_POINT_ON_SINGLE_LINE = 35;
}

enum CategoryType {
    CATEGORY_TYPE_CATEGORY_UNKNOWN = 0;

    CATEGORY_TYPE_CATEGORY_UNDERGROUND_OR_METRO = 1;
    CATEGORY_TYPE_CATEGORY_UNADVERTISED_PASSENGER = 2;
    CATEGORY_TYPE_CATEGORY_PASSENGER = 3; 
    CATEGORY_TYPE_CATEGORY_STAFF = 4;
    CATEGORY_TYPE_CATEGORY_MIXED = 5;

    CATEGORY_TYPE_CATEGORY_CHANNEL_TUNNEL = 6;
    CATEGORY_TYPE_CATEGORY_SLEEPER = 7;
    CATEGORY_TYPE_CATEGORY_INTERNATIONAL = 8;
    CATEGORY_TYPE_CATEGORY_MOTORAIL = 9;
    CATEGORY_TYPE_CATEGORY_UNADVERTISED_EXPRESS = 10;
    CATEGORY_TYPE_CATEGORY_EXPRESS = 11;
    CATEGORY_TYPE_CATEGORY_SLEEPER_DOMESTIC = 12;

    CATEGORY_TYPE_CATEGORY_BUS_REPLACEMENT = 13;
    CATEGORY_TYPE_CATEGORY_BUS_SERVICE = 14;

    CATEGORY_TYPE_CATEGORY_SHIP = 15;

    CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK = 16;
    CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK_UNDERGROUND_OR_METRO = 17;
    CATEGORY_TYPE_CATEGORY_EMPTY_COACHING_STOCK_OR_STAFF = 18;

    // Postal, Departmental, Light Locomotive, Railfreight Distribution, Trainload Freight, and Channel Tunnel Railfreight Distribution are all ommitted as they are not tracked by Darwin
}

enum AssociationCategory {
    ASSOCIATION_CATEGORY_UNKNOWN = 0;

    ASSOCIATION_CATEGORY_JOIN = 1;
    ASSOCIATION_CATEGORY_DIVIDE = 2;
    ASSOCIATION_CATEGORY_LINK = 3;
    ASSOCIATION_CATEGORY_NEXT = 4;
}
