syntax = "proto3";
option go_package = "github.com/headblockhead/railreader-grpc";

import "updateLocationsRequest.proto";
import "updateLocationsResponse.proto";
import "searchRequest.proto";
import "searchResponse.proto";
import "overviewRequest.proto";
import "overviewResponse.proto";
import "describeRequest.proto";
import "describeResponse.proto";

service RailReader {
    rpc UpdateLocations(UpdateLocationsRequest) returns (UpdateLocationsResponse) {} // Keep your location data list up-to-date. Call at least once per day.
    rpc Search(SearchRequest) returns (stream SearchResponse) {} // Search for train services. Designed to occupy minimal bandwidth.
    rpc Describe(stream DescribeRequest) returns (stream DescribeResponse) {} // Get detailed information about specific train service(s).
}
