syntax = "proto3";
option go_package = "github.com/headblockhead/railreader-grpc";

message SchedulesAtLocationRequest {
    string location_id = 1; // TIPLOC                            
}

// This contains some minimal information about a schedule at the location requested.
// Designed to use very little bandwidth.
// More (useful) data can be requested using the IDs provided.
message SchedulesAtLocationResponse {
    string schedule_uuid = 1;
    string schedule_id = 2;
    string schedule_location_uuid = 3;
    string scheduled_start_date = 4; // in YYYY-MM-DD format
}
