syntax = "proto3";
option go_package = "github.com/headblockhead/railreader-grpc";

import "railtypes.proto";

// From and To times are inclusive, and may return services scheduled up to 2 hours before and after the provided times to allow for services that are running early or late to be shown in the results.
message SearchRequest {
    repeated string location_ids = 1;

    string from_time = 2;
    string to_time = 3;
}

message SearchResponse {
    string location_id = 1;
    Schedule schedule = 2;
    ScheduleLocation schedule_location = 3;
    optional Forecast forecast = 4;

    reserved 5 to 6;

    optional string generous_arrival_time = 7;
    optional string generous_passing_time = 8;
    optional string generous_departure_time = 9;

    optional string platform = 10; 
}

message DisruptionReason {
    uint32 reason_id = 1;
    optional string reason_location_id = 2;
    // When true, the provided reason_id is 'near to' the provided reason_location_id. 
    // When false, the reason_id is 'at' the reason_location_id.
    bool reason_is_near_location = 3;  
}

message Schedule {
    string schedule_id = 1;
    string uid = 2;
    string headcode = 3;
    optional string retail_service_id = 4;
    string toc_id = 5;
    ServiceType service_type = 6;
    CategoryType category_type = 7;
    bool is_passenger = 8;
    bool is_active = 9;
    bool is_chartered = 10;
    bool schedule_is_cancelled = 11;
    optional DisruptionReason schedule_cancellation_reason = 12;
    optional string schedule_diverted_via_location_id = 13;
    optional DisruptionReason schedule_diversion_reason = 14;
}

// 'Working' times are used internally by staff
// 'Public' times are used for display to passengers
// Working and Public timetables may differ, typically to allow services to experience very minor (30 to 60s) delays without appearing late to the public.
// There is no scheduled_public_passing_time because locations through which a service passes without stopping do not need to display any times to the public.
message ScheduleLocation {
    repeated ActivityType activities = 1;
    repeated ActivityType planned_activities = 2;
    bool location_is_affected_by_diversion = 3;
    enum LocationType {
        LOCATION_TYPE_LOCATION_UNKNOWN = 0;
        LOCATION_TYPE_LOCATION_ORIGIN = 1;
        LOCATION_TYPE_LOCATION_OPERATIONAL_ORIGIN = 2;
        LOCATION_TYPE_LOCATION_INTERMEDIATE = 3;
        LOCATION_TYPE_LOCATION_OPERATIONAL_INTERMEDIATE = 4;
        LOCATION_TYPE_LOCATION_INTERMEDIATE_PASSING = 5;
        LOCATION_TYPE_LOCATION_DESTINATION = 6;
        LOCATION_TYPE_LOCATION_OPERATIONAL_DESTINATION = 7;
    }
    LocationType location_type = 4;
    optional string scheduled_working_arrival_time = 5;
    optional string scheduled_working_passing_time = 6; 
    optional string scheduled_working_departure_time = 7; 
    optional string scheduled_public_arrival_time = 8; 
    optional string scheduled_public_departure_time = 9;
    uint32 routing_delay = 10; // in minutes
    bool location_is_cancelled = 11;
    optional DisruptionReason location_cancellation_reason = 12;
}

// estimated_public_*_time and estimated_working_*_time are Darwin's estimations of the most likely times.
// estimated_minimum_*_time is Darwin's estimation of the first possible times.
// actual_*_time are time reports from the physical train
message Forecast {
    bool is_reverse_formation = 1;
    optional DisruptionReason schedule_late_reason = 2;

    optional string estimated_public_arrival_time = 3; 
    optional string estimated_working_arrival_time = 4;
    optional string estimated_minimum_arrival_time = 5;
    optional bool arrival_is_delayed = 6;
    optional bool arrival_is_delayed_by_unknown_amount = 7;
    optional string estimated_passing_time = 8;
    optional string estimated_minimum_passing_time = 9;
    optional bool passing_is_delayed = 10;
    optional bool passing_is_delayed_by_unknown_amount = 11;
    optional string estimated_public_departure_time = 12; 
    optional string estimated_working_departure_time = 13;
    optional string estimated_minimum_departure_time = 14;
    optional bool departure_is_delayed = 15;
    optional bool departure_is_delayed_by_unknown_amount = 16;

    optional string actual_arrival_time = 17;
    optional string actual_arrival_data_class = 18;
    optional string actual_arrival_data_source = 19;
    optional string actual_arrival_data_source_system = 20;
    optional string actual_passing_time = 21; 
    optional string actual_passing_data_class = 22;
    optional string actual_passing_data_source = 23;
    optional string actual_passing_data_source_system = 24;
    optional string actual_departure_time = 25; 
    optional string actual_departure_data_class = 26;
    optional string actual_departure_data_source = 27;
    optional string actual_departure_data_source_system = 28;
  
    optional DisruptionReason location_late_reason = 29;
    optional string location_disruption_risk = 30;
    optional DisruptionReason location_disruption_risk_reason = 31;

    optional string affected_by = 32;

    optional bool platform_is_suppressed = 33; // do not display platform information if true
    optional bool platform_is_suppressed_by_cis = 34;
    enum PlatformDataSource {
        PLATFORM_DATA_SOURCE_PLATFORM_UNKNOWN = 0;
        PLATFORM_DATA_SOURCE_PLATFORM_PLANNED = 1;
        PLATFORM_DATA_SOURCE_PLATFORM_AUTOMATIC = 2;
        PLATFORM_DATA_SOURCE_PLATFORM_MANUAL = 3;
    }
    optional PlatformDataSource platform_data_source = 35;
    optional bool platform_is_confirmed = 36;

    bool service_is_suppressed = 37;
    bool service_detatches_from_front = 38;
}

