syntax = "proto3";
option go_package = "github.com/headblockhead/railreader-grpc";

// SearchRequest is sent once.
message SearchRequest {
    string at_location_id = 1; // Must be provided. Only services that visit this location_id in their route will be returned.
    reserved 2; // TODO: CRS lookup

    string from_time = 3; // Services scheduled up to 2 hours before the from_time may be returned if they are delayed.
    string to_time = 4; // Services scheduled up to 2 hours after the to_time may be returned if they are early.

    bool include_non_passenger_services = 5; // If true, all services will be returned. If false or unspecified, only passenger services will be returned.
    bool exclude_non_active_services = 6; // If true, only active services will be returned. If false or unspecified, all services will be returned. A service being "inactive" indicates that it is unlikely to recieve any future data updates (altough this is not a guarentee), and/or that the train is not expected to run.
    bool include_chartered_services = 7; // If true, all services will be returned. If false or unspecified, only non-chartered services will be returned. 
 
    enum Type {
      TYPE_UNKNOWN = 0;
      TYPE_ARRIVALS = 1;
      TYPE_PASSING = 2;
      TYPE_DEPARTURES = 3;
    }
    optional Type include_only_type = 8; // If specified, only services that arrive/pass/depart the requested location will be returned. If unspecified, all services will be returned.

    // TODO: use CRS instead here?
    repeated string must_stop_at_passenger_location_ids = 9; // If any are specified, only services that have a passenger stop at all of these location_ids in their route will be returned. If unspecified, all services will be returned.
                                                        // This is affected by the include_only_type field: ARRIVALS will only consider stops that come before the requested location, DEPARTURES will only consider stops that come after the requested location, PASSING and unspecified type will consider stops in both directions.
    repeated string must_visit_location_ids = 10; // If any are specified, only services that visit all of these location_ids in their route will be returned. If unspecified, all services will be returned.
                                             // This is affected by the include_only_type field: ARRIVALS will only consider route entries that come before the requested location, DEPARTURES will only consider route entries that come after the requested location, PASSING and unspecified type will consider route entries in both directions.
}
