syntax = "proto3";
option go_package = "github.com/headblockhead/railreader-grpc";

// UpdateLocationsResponse is sent once.
message UpdateLocationsResponse {
    // Describes an update made to a location at a point in time.
    message LocationUpdate {
        string location_id = 1; // The location_id affected by this update.
        string reference_file_id = 2; // The reference_file_id at which this update occurred. 
        bool is_deleted = 3; // The new deletion status of the location after this update.
        optional string crs_id = 4; // The new crs_id of the location after this update. If not provided, the crs_id is null after this update.
        optional string toc_id = 5; // The new toc_id of the location after this update. If not provided, the toc_id is null after this update.
        string name = 6; // The new name of the location after this update.
    }
    repeated LocationUpdate updates = 1; // All (if any) updates between the current_reference_file_id in UpdateLocationsRequest and the new_reference_file_id in this response.
    string new_reference_file_id = 2; // The lastest reference_file_id equivalent you will have after applying all updates given.
}
