syntax = "proto3";
option go_package = "github.com/headblockhead/railreader-grpc";

message UpdateLocationsRequest {
    optional string current_reference_file_id = 1; // If not specified, all updates will be returned.
}

message UpdateLocationsResponse {
    repeated LocationUpdate updates = 1; // All (if any) updates between the current_reference_file_id in UpdateLocationsRequest and the new_reference_file_id in this response.
    string new_reference_file_id = 2; // The lastest reference_file_id equivalent you will have after applying all updates.
}

// An update made to a location at a point in time.
// Provides the new state for a given location_id, and the reference_file_id at which this change occurred.
message LocationUpdate {
    string location_id = 1; // The location_id affected
    string reference_file_id = 2; // The reference_file_id at which this change occurred. 
    bool is_deleted = 3; 
    optional string crs_id = 4;
    optional string toc_id = 5;
    string name = 6;
}
